name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Only on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -R # Helps verify the folder structure

      - name: Check for USE_CICD in commit message
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" != *"[USE_CICD]"* ]]; then
            echo "Commit message does not contain USE_CICD. Aborting."
            exit 1
          fi

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: dotnet restore CodeMonkeys.CMS.Public.sln # Use the correct solution file

      - name: Clean solution
        run: dotnet clean CodeMonkeys.CMS.Public.sln --configuration Release

      - name: Build solution
        run: dotnet build CodeMonkeys.CMS.Public.sln --configuration Release --no-restore --verbosity detailed

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.head_commit.message, '[USE_CICD]')

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages for the solution
        run: dotnet restore CodeMonkeys.CMS.Public.sln

      - name: Clean solution
        run: dotnet clean CodeMonkeys.CMS.Public.sln --configuration Release

      - name: Build the solution
        run: dotnet build CodeMonkeys.CMS.Public.sln --configuration Release --no-restore --verbosity detailed

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Set environment variable for connection string
        run: echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Deploy database migrations
        run: |
          cd CodeMonkeys.CMS.Public.Shared
          # List the files to ensure deps.json exists
          ls -R bin/Release/net8.0/ || echo "Directory not found"
          dotnet ef database update --no-build --context ApplicationDbContext --configuration Release
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
